// this interface is for the sortable letters widget on the play page...
// the interface name is hard coded into the code for the widget...
// I need to edit the source, and fix the lame naming convention and make it customizable...
export interface ItemType {
	id: number
	name: string
}
